---
- name: dlFusionMiddleware
  hosts: all
  become: true
  become_method: sudo
  vars:
    outputDir: /vagrant_downloads
  vars_prompt:
    - name: "oracleLogin"
      prompt: "What is youir Oracle Software Delivery Cloud login"
      private: no

    - name: "oraclePass"
      prompt: "What is youir Oracle Software Delivery Cloud password"
      private: yes


  tasks:
  - name: get Fusion Middleware infrastructure
    script: wgetFusionMiddleware.sh {{ oracleLogin }} {{ oraclePass }} {{ outputDir }} V886426-01
    args:
      creates: "{{ outputDir }}/V886426-01.zip"

  - name: get Oracle Data Integrator
    script: wgetOracleDataIntegrator.sh {{ oracleLogin }} {{ oraclePass }} {{ outputDir }} V886451-01
    args:
      creates: "{{ outputDir }}/V886451-01{{item}}.zip"
    with_items:
    - _1of2
    - _2of2
