---
- name: dlFusionMiddleware
  hosts: all
  become: true
  become_method: sudo
  vars:
    outputDir: /vagrant_downloads
  vars_prompt:
    - name: "oracleLogin"
      prompt: "What is youir Oracle Software Delivery Cloud login"
      private: no

    - name: "oraclePass"
      prompt: "What is youir Oracle Software Delivery Cloud password"
      private: yes


  tasks:


  - name: get Oracle JDeveloper
    script: wgetJDeveloper.sh {{ oracleLogin }} {{ oraclePass }} {{ outputDir }} {{item}}
    args:
      creates: "{{ outputDir }}/{{item}}.zip"
    with_items:
    - V840994-01_1of2
    - V840994-01_2of2
